"use strict";

const js = require("@eslint/js");
const globals = require("globals");

module.exports = [
    {
        ignores: ["build/**", "promo/**", ".claude/**", "node_modules/**", "eslint.config.js"]
    },
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "script",
            globals: {
                ...globals.browser,
                ...globals.webextensions,
                // Cross-file globals: redirect.js → all other scripts
                Redirect: "writable",
                // Cross-file globals: util.js → page scripts
                dataBind: "writable",
                show: "writable",
                hide: "writable",
                el: "writable",
                showForm: "writable",
                hideForm: "writable",
                showMessage: "writable",
                hideMessage: "writable",
                move: "writable",
                // Cross-file globals: redirectorpage.js → editredirect.js, importexport.js, organizemode.js
                REDIRECTS: "writable",
                saveChanges: "writable",
                renderRedirects: "writable",
                updateBindings: "writable",
                template: "writable",
                options: "writable"
            }
        },
        rules: {
            "accessor-pairs": "error",
            "array-bracket-spacing": ["error", "never"],
            "array-callback-return": "error",
            "arrow-spacing": ["error", { "after": true, "before": true }],
            "block-scoped-var": "error",
            "block-spacing": "error",
            "camelcase": ["error", { "properties": "never" }],
            "comma-dangle": "error",
            "comma-spacing": ["error", { "after": true, "before": false }],
            "comma-style": ["error", "last"],
            "computed-property-spacing": ["error", "never"],
            "consistent-return": "off",
            "default-param-last": "error",
            "dot-location": "error",
            "dot-notation": ["error", { "allowKeywords": true }],
            "eol-last": ["error", "never"],
            "eqeqeq": "off",
            "func-call-spacing": "error",
            "func-name-matching": "error",
            "func-style": "off",
            "grouped-accessor-pairs": "error",
            "id-match": "error",
            "key-spacing": "error",
            "keyword-spacing": ["error", { "after": true, "before": true }],
            "linebreak-style": "off",
            "max-depth": "error",
            "max-nested-callbacks": "error",
            "max-statements-per-line": "error",
            "new-cap": "error",
            "new-parens": "error",
            "no-alert": "error",
            "no-array-constructor": "error",
            "no-bitwise": "error",
            "no-caller": "error",
            "no-confusing-arrow": "error",
            "no-console": "off",
            "no-constructor-return": "error",
            "no-div-regex": "error",
            "no-dupe-else-if": "error",
            "no-duplicate-imports": "error",
            "no-else-return": "error",
            "no-empty-function": "error",
            "no-eq-null": "error",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-label": "error",
            "no-floating-decimal": "error",
            "no-implicit-coercion": "error",
            "no-implicit-globals": "off",
            "no-implied-eval": "error",
            "no-import-assign": "error",
            "no-inline-comments": "off",
            "no-iterator": "error",
            "no-label-var": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-loop-func": "error",
            "no-magic-numbers": "off",
            "no-mixed-operators": "error",
            "no-multi-assign": "error",
            "no-multi-spaces": "error",
            "no-multi-str": "error",
            "no-multiple-empty-lines": "error",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-object": "error",
            "no-new-wrappers": "error",
            "no-octal-escape": "error",
            "no-param-reassign": "error",
            "no-plusplus": "off",
            "no-proto": "error",
            "no-redeclare": ["error", { "builtinGlobals": false }],
            "no-restricted-globals": "error",
            "no-restricted-properties": "error",
            "no-restricted-syntax": "error",
            "no-return-assign": "error",
            "no-script-url": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-setter-return": "error",
            "no-shadow": "error",
            "no-template-curly-in-string": "error",
            "no-throw-literal": "error",
            "no-undef-init": "error",
            "no-undefined": "off",
            "no-unmodified-loop-condition": "error",
            "no-unneeded-ternary": "error",
            "no-unused-expressions": ["error", { "allowTernary": true }],
            "no-unused-vars": ["error", { "vars": "local", "caughtErrors": "none" }],
            "no-use-before-define": "off",
            "no-useless-call": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "error",
            "no-void": "error",
            "no-warning-comments": "off",
            "no-whitespace-before-property": "error",
            "object-curly-spacing": ["error", "always"],
            "object-shorthand": "error",
            "one-var-declaration-per-line": "error",
            "operator-assignment": ["error", "always"],
            "operator-linebreak": "error",
            "prefer-const": "error",
            "prefer-exponentiation-operator": "error",
            "prefer-numeric-literals": "error",
            "prefer-promise-reject-errors": ["error", { "allowEmptyReject": true }],
            "prefer-regex-literals": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "error",
            "quotes": ["error", "double"],
            "radix": "error",
            "require-await": "error",
            "rest-spread-spacing": ["error", "never"],
            "semi": "error",
            "semi-spacing": "error",
            "semi-style": ["error", "last"],
            "sort-imports": "off",
            "sort-vars": "off",
            "space-before-blocks": "error",
            "space-in-parens": ["error", "never"],
            "space-infix-ops": "error",
            "space-unary-ops": "error",
            "spaced-comment": ["error", "always"],
            "switch-colon-spacing": "error",
            "symbol-description": "error",
            "template-curly-spacing": "error",
            "unicode-bom": ["error", "never"],
            "vars-on-top": "off",
            "wrap-iife": "error",
            "wrap-regex": "error",
            "yield-star-spacing": "error",
            "yoda": ["error", "never"]
        }
    }
];
